name: Frames & Frequencies
title: Frames & Frequencies | The blog of Arya
description: This is the blog of Arya Pandit, make yourself at home!
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: aryapandit200408@gmail.com
# See: https://disqus.com/
disqus_username: https://disqus.com/by/arya_pandit/
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: https://formspree.io/f/xqedzyyv
